apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: microservices
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - app: nginx-demo
            namespace: demo
          - app: redis
            namespace: data
          - app: monitoring
            namespace: observability
  template:
    metadata:
      name: "{{app}}"
    spec:
      project: default
      source:
        repoURL: https://github.com/jverger/argocd
        targetRevision: main
        path: "config-repo/{{app}}"        # ← chemin = nom de l'app
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true