apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base   # Hérite de la base
patches:
  - path: patch-replicas.yaml
  - path: patch-resources.yaml
images:
  - name: nginx
    newTag: "1.27.4"   # Version épinglée en production
