apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io  # Nettoyage à la suppression
spec:
  project: default
  source:
    repoURL: https://github.com/jverger/argocd
    targetRevision: main
    path: config-repo/nginx-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: demo-application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true